import com.github.mdp.dns_leak.DNSSerializer;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mdp' at '5/1/14 1:50 PM' with Gradle 1.12
 *
 * @author mdp, @date 5/1/14 1:50 PM
 */
public class DNSSerializerTest {
    @Test public void testDNSSerializerMethod() {
        DNSSerializer dnsSerializer = new DNSSerializer("d.mdp.im", "uuid");
        assertTrue(true);
    }
}
